#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

# Load environment variables from .env file
env_path = Path(__file__).resolve().parents[3] / ".env"
if env_path.exists():
    from dotenv import load_dotenv

    load_dotenv(env_path)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "output"
SKILLS_ROOT = ROOT.parent


class OrchestrationError(Exception):
    """Exception raised for errors in orchestration."""


def parse_unit_column(layout_code: str) -> int:
    """Extract unit_column from layout_code like T-3:9."""
    match = re.search(r":(\d+)$", str(layout_code).strip())
    return int(match.group(1)) if match else 0



def read_json(path: Path) -> Any:
    """Read JSON from file."""
    return json.loads(path.read_text(encoding="utf-8-sig"))



def write_json(data: Any, path: Path) -> None:
    """Write JSON to file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")



def get_skill_path(skill_name: str) -> Path:
    """Get the path to a skill directory."""
    skill_path = SKILLS_ROOT / skill_name
    if not skill_path.exists():
        raise OrchestrationError(f"Skill not found: {skill_name}")
    return skill_path



def call_add_solid(step: Dict[str, Any]) -> Dict[str, Any]:
    """Call fdu-add-solid-json skill."""
    skill_path = get_skill_path("fdu-add-solid-json")
    script_path = skill_path / "scripts" / "generate_add_solid_json.py"

    if not script_path.exists():
        raise OrchestrationError(f"Script not found: {script_path}")

    # Create a temporary JSON file with the step data
    temp_file = skill_path / "KB" / "temp_step.json"
    write_json(step, temp_file)

    try:
        subprocess.run(
            [sys.executable, str(script_path), str(temp_file)],
            capture_output=True,
            text=True,
            check=True,
            cwd=str(skill_path),
        )

        output_files = list((skill_path / "output").glob("generated_add_solid_*.json"))
        if not output_files:
            raise OrchestrationError("No output file generated by fdu-add-solid-json")

        output_file = max(output_files, key=lambda p: p.stat().st_mtime)
        return read_json(output_file)
    except subprocess.CalledProcessError as e:
        raise OrchestrationError(f"Failed to call fdu-add-solid-json: {e.stderr}") from e



def call_add_liquid(step: Dict[str, Any]) -> Dict[str, Any]:
    """Call fdu-add-liquid-json skill."""
    skill_path = get_skill_path("fdu-add-liquid-json")
    script_path = skill_path / "scripts" / "generate_add_liquid_json.py"

    if not script_path.exists():
        raise OrchestrationError(f"Script not found: {script_path}")

    # Create a temporary JSON file with step data
    temp_file = skill_path / "KB" / "temp_step.json"
    write_json(step, temp_file)

    try:
        subprocess.run(
            [sys.executable, str(script_path), str(temp_file)],
            capture_output=True,
            text=True,
            check=True,
            cwd=str(skill_path),
        )

        output_files = list((skill_path / "output").glob("generated_add_liquid_*.json"))
        if not output_files:
            raise OrchestrationError("No output file generated by fdu-add-liquid-json")

        output_file = max(output_files, key=lambda p: p.stat().st_mtime)
        return read_json(output_file)
    except subprocess.CalledProcessError as e:
        raise OrchestrationError(f"Failed to call fdu-add-liquid-json: {e.stderr}") from e



def call_reaction_control(step: Dict[str, Any]) -> Dict[str, Any]:
    """Call fdu-reaction-control-json skill."""
    skill_path = get_skill_path("fdu-reaction-control-json")
    script_path = skill_path / "scripts" / "generate_reaction_control_json.py"

    if not script_path.exists():
        raise OrchestrationError(f"Script not found: {script_path}")

    # Create a temporary JSON file with step data
    temp_file = skill_path / "KB" / "temp_step.json"
    write_json(step, temp_file)

    try:
        subprocess.run(
            [sys.executable, str(script_path), str(temp_file)],
            capture_output=True,
            text=True,
            check=True,
            cwd=str(skill_path),
        )

        output_files = list((skill_path / "output").glob("generated_reaction_control_*.json"))
        if not output_files:
            raise OrchestrationError("No output file generated by fdu-reaction-control-json")

        output_file = max(output_files, key=lambda p: p.stat().st_mtime)
        return read_json(output_file)
    except subprocess.CalledProcessError as e:
        raise OrchestrationError(f"Failed to call fdu-reaction-control-json: {e.stderr}") from e



def call_filter(step: Dict[str, Any]) -> Dict[str, Any]:
    """Call fdu-filter-json skill."""
    skill_path = get_skill_path("fdu-filter-json")
    script_path = skill_path / "scripts" / "generate_filter_json.py"

    if not script_path.exists():
        raise OrchestrationError(f"Script not found: {script_path}")

    # Create a temporary JSON file with step data
    temp_file = skill_path / "KB" / "temp_step.json"
    write_json(step, temp_file)

    try:
        subprocess.run(
            [sys.executable, str(script_path), str(temp_file)],
            capture_output=True,
            text=True,
            check=True,
            cwd=str(skill_path),
        )

        output_files = list((skill_path / "output").glob("generated_filter_*.json"))
        if not output_files:
            raise OrchestrationError("No output file generated by fdu-filter-json")

        output_file = max(output_files, key=lambda p: p.stat().st_mtime)
        return read_json(output_file)
    except subprocess.CalledProcessError as e:
        raise OrchestrationError(f"Failed to call fdu-filter-json: {e.stderr}") from e


def call_high_filter(step: Dict[str, Any]) -> Dict[str, Any]:
    """Call fdu-high-filter-json skill."""
    skill_path = get_skill_path("fdu-high-filter-json")
    script_path = skill_path / "scripts" / "generate_high_filter_json.py"

    if not script_path.exists():
        raise OrchestrationError(f"Script not found: {script_path}")

    # Create a temporary JSON file with step data
    temp_file = skill_path / "KB" / "temp_step.json"
    write_json(step, temp_file)

    try:
        subprocess.run(
            [sys.executable, str(script_path), str(temp_file)],
            capture_output=True,
            text=True,
            check=True,
            cwd=str(skill_path),
        )

        output_files = list((skill_path / "output").glob("generated_high_filter_*.json"))
        if not output_files:
            raise OrchestrationError("No output file generated by fdu-high-filter-json")

        output_file = max(output_files, key=lambda p: p.stat().st_mtime)
        return read_json(output_file)
    except subprocess.CalledProcessError as e:
        raise OrchestrationError(f"Failed to call fdu-high-filter-json: {e.stderr}") from e



def process_step(step: Dict[str, Any]) -> Dict[str, Any]:
    """Process a single step and return its execution protocol."""
    unit_type = step.get("unit_type")
    skill_input = step.get("skill_input", {})

    if not unit_type:
        raise OrchestrationError(f"Step missing unit_type")
    if not skill_input:
        raise OrchestrationError(f"Step missing skill_input")

    # Create a step object with resource_info if available
    step_data = {"skill_input": skill_input}
    if "resource_info" in step:
        step_data["resource_info"] = step["resource_info"]

    if unit_type == "exp_add_solid":
        action = call_add_solid(step_data)
    elif unit_type == "exp_pipetting":
        action = call_add_liquid(step_data)
    elif unit_type == "exp_magnetic_stirrer":
        action = call_reaction_control(step_data)
    elif unit_type == "exp_filtering_samples":
        action = call_filter(step_data)
    elif unit_type == "exp_high_filtering_samples":
        action = call_high_filter(step_data)
    else:
        raise OrchestrationError(f"Unknown unit_type: {unit_type}")

    return action



def orchestrate_steps(steps: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Orchestrate multiple steps and return the execution protocol."""
    protocol = []

    for step in steps:
        action = process_step(step)
        skill_input = step.get("skill_input", {})
        layout_code = str(action.get("layout_code", "")).strip()
        action["unit_column"] = parse_unit_column(layout_code)
        if isinstance(skill_input, dict) and "unit_row" in skill_input:
            action["unit_row"] = skill_input["unit_row"]
        protocol.append(action)
    return protocol



def generate_orchestration_json(
    step_json_path: Path,
    output_path: Path | None = None,
) -> tuple[List[Dict[str, Any]], Path]:
    """Generate orchestration JSON from step JSON."""
    step_json = read_json(step_json_path)
    steps = step_json.get("steps", [])

    if not steps:
        raise OrchestrationError("No steps found in step JSON")

    protocol = orchestrate_steps(steps)

    if output_path is None:
        timestamp = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
        output_path = OUTPUT_DIR / f"generated_protocol_{timestamp}.json"

    write_json(protocol, output_path)
    return protocol, output_path
