"""Default allene-review taxonomy profile shared by metadata and retrieval."""

discovery_normalization = {
    "phrase_rewrites": [
        [
            r"(?<![A-Za-z0-9])(?:[A-Za-z]+-)?\d+-en-\d+-ynes?(?![A-Za-z0-9])",
            " conjugated enyne ",
        ],
        [r"\benynes\b", "enyne"],
        [
            r"\bpropargylic\s+(?:mesylates?|tosylates?|carbonates?|acetates?|esters?|halides?|bromides?|chlorides?|phosphates?|sulfides?)\b",
            r"\g<0> propargylic alcohol derivative",
        ],
    ],
    "family_prefix_aliases": [
        ["allenoat", "allene"],
        ["allenol", "allene"],
        ["allenyl", "allene"],
    ],
    "systematic_family_patterns": [
        ["allene", r"(?<!\d)2\s*,\s*3\s*[-‐‑‒–—]?\s*[A-Za-z0-9()\-]{0,40}dien"],
    ],
}

rules = [
        # 1. Products
        ('allenes', 'product', ['allene', 'allenes', '1,2-diene', 'cumulated diene']),
        ('axially chiral allenes', 'product', ['axially chiral allene', 'chiral allene', 'enantioenriched allene', 'optically active allene']),
        ('monosubstituted allenes', 'product', ['terminal allene', 'monosubstituted allene', '1-substituted allene']),
        ('1,3-disubstituted allenes', 'product', ['1,3-disubstituted allene', 'disubstituted allene']),
        ('polysubstituted allenes', 'product', ['polysubstituted allene', 'multisubstituted allene', 'substituted allene']),
        ('trisubstituted allenes', 'product', ['trisubstituted allene', 'tri-substituted allene']),
        ('tetrasubstituted allenes', 'product', ['tetrasubstituted allene', 'fully substituted allene']),
        ('terminal allenes', 'product', ['terminal allene', '1,1-disubstituted terminal allene', 'geminally disubstituted allene']),
        ('haloallenes', 'product', ['chloroallene', 'haloallene', 'bromoallene', 'iodoallene']),
        ('arylallenes', 'product', ['arylallene', 'diarylallene', 'aryl-substituted allene']),
        ('alkylallenes', 'product', ['alkylallene', 'dialkylallene', 'trialkylallene']),
        ('allenoates', 'product', ['allenoate', 'allenoates', 'allenecarboxylate', 'allenic ester']),
        ('allenic carboxylic acids', 'product', ['allenoic acid', 'allenic acid', 'allenecarboxylic acid']),
        ('allenyl carboxylic acids', 'product', ['allene carboxylic acid', 'allenyl carboxylic acid', 'allencarboxylic acid']),
        ('alpha-allenic alcohols', 'product', ['alpha-allenic alcohol', 'α-allenic alcohol', 'allenyl alcohol', 'allenol']),
        ('allenyl amines', 'product', ['allenyl amine', 'allenylamine', 'aminoallene', 'homoallenylamine']),
        ('allenyl sulfones', 'product', ['allenyl sulfone', '1,2-allenyl sulfone']),
        ('allenyl boranes', 'product', ['allenylborane', 'axially chiral allenylborane', 'butadienyl borane']),
        ('allenyl silanes', 'product', ['allenylsilane', 'axially chiral allenylsilane', 'trichloroallenylsilane']),
        ('allenylmethylsilanes', 'product', ['allenylmethylsilane', 'allenylmethyl silane', 'silyl-substituted allene']),
        ('vinylallenes and cumulenes', 'product', ['vinylallene', 'divinylallene', 'heptatetraene', 'cumulene']),
        ('butatrienes', 'product', ['butatriene', 'substituted butatriene', '1,4-disubstituted butatriene']),
        ('allenic ketones and ethers', 'product', ['allenic ketone', 'allenyl ketone', 'allenic ether', 'allenyl ether']),
        ('allene-derived cyclic products', 'product', ['allene-derived heterocycle', 'allene-derived carbocycle', 'cyclic allene product']),
        ('allene-containing natural products', 'product', ['allenic natural product', 'allene-containing natural product', 'allenic pheromone']),

        # 2. Substrates
        ('propargylic alcohols', 'substrate', ['propargylic alcohol', 'propargyl alcohol', 'ethynyl tertiary alcohol', 'ethynyl tertiary alcohols', 'alkynyl tertiary alcohol', 'alkynyl tertiary alcohols', 'azaarylethynyl tertiary alcohol', 'azaarylethynyl tertiary alcohols']),
        ('activated propargylic derivatives', 'substrate', ['propargylic alcohol derivative', 'propargylic alcohol derivatives', 'propargylic carbonate', 'propargylic carbonates', 'propargylic mesylate', 'propargylic mesylates', 'propargylic phosphate', 'propargylic phosphates', 'propargylic acetate', 'propargylic acetates', 'propargylic benzoate', 'propargylic benzoates', 'propargylic carbamate', 'propargylic carbamates', 'propargylic ester', 'propargylic esters', 'propargylic halide', 'propargylic halides', 'propargylic substrate', 'propargylic substrates']),
        ('propargylic acetates', 'substrate', ['propargylic acetate', 'propargyl acetate', 'propargylic benzoate', 'propargylic benzoates', 'ethynylcarbinol acetate']),
        ('propargylic mesylates', 'substrate', ['propargylic mesylate', 'propargyl mesylate', 'propynyl methanesulfonate']),
        ('propargylic sulfinates and sulfonates', 'substrate', ['propargylic sulfinate', 'propargylic sulfonate', 'propargylic tosylate']),
        ('propargylic carbonates', 'substrate', ['propargylic carbonate', 'propargyl carbonate']),
        ('propargylic phosphates', 'substrate', ['propargylic phosphate', 'propargyl phosphate']),
        ('propargylic halides', 'substrate', ['propargylic bromide', 'propargyl bromide', 'propargylic chloride', 'propargyl halide']),
        ('propargylic dichlorides', 'substrate', ['propargylic dichloride', '1,1-dichloro propargylic', 'propargyl gem-dichloride']),
        ('propargylic ethers', 'substrate', ['propargylic ether', 'propargyl ether', 'alkoxy alkyne']),
        ('propargylic epoxides', 'substrate', ['propargylic epoxide', 'ethynyl epoxide', 'alkynyl epoxide']),
        ('propargylic carbamates', 'substrate', ['propargylic carbamate', 'propynyl carbamate']),
        ('propargylic amines', 'substrate', ['optically active propargylamine', 'chiral propargylamine', 'propargylic amine']),
        ('allenyl acetates', 'substrate', ['allenyl acetate', '2,3-allenyl acetate', 'allenic acetate']),
        ('allenyl phosphates', 'substrate', ['allenyl phosphate', '2,3-allenyl phosphate', 'allenic phosphate']),
        ('allenoic acids', 'substrate', ['2,3-allenoic acid', 'allenoic acid', 'allenic acid']),
        ('allenic acids and esters', 'substrate', ['allenic acid', 'allenic ester', 'allenoate']),
        ('allenoates', 'substrate', ['2,3-allenoate', 'allenoate', 'allenic ester']),
        ('allenic alcohols', 'substrate', ['allenic alcohol', 'allenol', 'allenic diol', 'allene diol']),
        ('alkynoates', 'substrate', ['alkynoate', 'alkynoates', '3-alkynoate', '3-alkynoates', 'alkynoic ester']),
        ('preformed substituted allenes', 'substrate', ['preformed allene', 'substituted allene substrate', '1-alkylallene-1,3-dicarboxylate', '1-alkylallene-1,3-dicarboxylates', 'tetrasubstituted allene', 'allene hydrocarbon', 'racemic allene', 'racemic axially chiral allene', 'kinetic resolution of axially chiral allenes', 'dynamic kinetic resolution of axially chiral allenes']),
        ('silyl-substituted diene precursors', 'substrate', ['3-bromo-5-silylpenta-1,3-diene', '3-bromo-5-silylpenta-1,3-dienes', 'allenylmethylsilane', 'allenylmethylsilanes', 'allenylmethyl silane']),
        ('enynes', 'substrate', ['enyne', 'enynes', 'activated enyne', 'activated enynes', 'allenyne', '1,3-enyne', '1,3-enynes', 'but-1-en-3-yne', 'but-1-en-3-ynes', 'enynamide', 'enynamides', 'enynone', 'enynones']),
        ('enol triflates', 'substrate', ['enol triflate', 'enol triflates', 'vinyl triflate', 'vinyl triflates']),
        ('rearrangement precursors', 'substrate', ['propargyl claisen rearrangement', 'propargylic claisen rearrangement', 'myers allene synthesis', 'propargylic rearrangement precursor']),
        ('ketenes', 'substrate', ['ketene', 'substituted ketene']),
        ('terminal alkynes', 'substrate', ['terminal alkyne', '1-alkyne', '1-alkynes', 'acetylene substrate']),
        ('aldehydes', 'substrate', ['aliphatic aldehyde', 'aromatic aldehyde', 'benzaldehyde']),
        ('ketones', 'substrate', ['ketone', 'dialkyl ketone', 'aryl alkyl ketone']),

        # 3. Central metals, catalysts, and enabling methods
        ('copper catalysis', 'catalyst_or_method', ['Cu', 'CuI', 'CuBr', 'CuBr2', 'copper-catalyzed', 'copper catalysis', 'cu(i)', 'cu(ii)', 'copper complex', 'organocopper', 'organocuprate', 'lithium dialkylcuprate', 'gilman reagent']),
        ('palladium catalysis', 'catalyst_or_method', ['Pd', 'palladium-catalyzed', 'palladium catalysis', 'pd(0)', 'pd(ii)', 'palladium complex']),
        ('gold catalysis', 'catalyst_or_method', ['Au', 'gold-catalyzed', 'gold catalysis', 'au(i)', 'au(iii)', 'gold complex']),
        ('platinum catalysis', 'catalyst_or_method', ['Pt', 'platinum-catalyzed', 'platinum catalysis', 'pt(ii)', 'platinum complex']),
        ('rhodium catalysis', 'catalyst_or_method', ['Rh', 'rhodium-catalyzed', 'rhodium catalysis', 'rh(i)', 'rhodium complex']),
        ('iridium catalysis', 'catalyst_or_method', ['Ir', 'iridium-catalyzed', 'iridium catalysis', 'ir(i)', 'iridium complex']),
        ('iron catalysis', 'catalyst_or_method', ['Fe', 'iron-catalyzed', 'iron porphyrin', 'fe(tcp)cl', 'iron carbene']),
        ('nickel catalysis', 'catalyst_or_method', ['Ni','nickel-catalyzed', 'nickel catalysis', 'ni(0)', 'nickel complex']),
        ('cobalt catalysis', 'catalyst_or_method', ['Co', 'cobalt-catalyzed', 'cobalt catalysis', 'cobalt complex']),
        ('ruthenium catalysis', 'catalyst_or_method', ['Ru', 'ruthenium-catalyzed', 'ruthenium catalysis', 'ruthenium complex']),
        ('silver catalysis', 'catalyst_or_method', ['Ag', 'Ag-catalyzed', 'silver(i)-mediated', 'agno3-mediated', 'agbf4', 'agotf']),
        ('zinc catalysis or mediation', 'catalyst_or_method', ['Zn', 'ZnBr2', 'ZnI2', 'Zn-catalyzed', 'zni2-mediated', 'zinc iodide']),
        ('cadmium catalysis', 'catalyst_or_method', ['Cd', 'CdI2', 'cdi2-mediated', 'cadmium iodide']),
        ('titanium mediation', 'catalyst_or_method', ['Ti', 'titanium-promoted', 'titanium-mediated', 'ti(oet)4', 'titanium tetraethoxide']),
        ('zirconium catalysis', 'catalyst_or_method', ['Zr', 'cp2zr(h)cl', 'schwartz reagent', 'zirconium hydride']),
        ('main-group metal mediation', 'catalyst_or_method', ['organolithium', 'organoaluminum', 'grignard reagent', 'main-group metal']),
        ('phase-transfer catalysis', 'catalyst_or_method', ['phase-transfer catalyst', 'phase-transfer catalysis', 'quaternary ammonium salt', 'chiral ammonium salt']),
        ('bifunctional organocatalysis', 'catalyst_or_method', ['bifunctional catalyst', 'bifunctional organocatalyst', 'hydrogen-bonding catalyst']),
        ('chiral phosphoric acid catalysis', 'catalyst_or_method', ['chiral phosphoric acid', 'bisphosphoric acid', 'phosphoric acid catalyst']),
        ('enzymatic catalysis', 'catalyst_or_method', ['lipase-catalyzed', 'esterase-catalyzed', 'porcine pancreatic lipase', 'pig liver esterase', 'chemoenzymatic', 'enzyme-metal cooperative', 'metal-enzyme cooperative']),

        # 4. Organometallic reaction partners
        ('Grignard reagents', 'organometallic_partner', ['grignard reagent', 'alkylmagnesium bromide', 'alkylmagnesium chloride', 'rmgbr', 'rmgcl']),
        ('organolithium reagents', 'organometallic_partner', ['organolithium', 'alkyllithium', 'methyllithium', 'butyllithium']),
        ('boranes and boronates', 'organometallic_partner', ['arylboronic acid', 'phenylboronic acid', 'alkylborane', 'alkyl-9-bbn', '9-bbn', 'alkylborate', 'arylboronate', 'arylboronic ester', 'arylboronic acid', 'alkenylboronate', 'alkenylboronic ester', 'vinylboronate']),
        ('triorganoindium reagents', 'organometallic_partner', ['triorganoindium', 'arylindium', 'alkenylindium']),
        ('allenylsamarium species', 'organometallic_partner', ['allenylsamarium', 'racemic allenylmetal species']),
        ('phenylzinc and alkylzinc reagents', 'organometallic_partner', ['phenylzinc bromide', 'ethylzinc bromide', 'dimethylzinc']),
        ('aryltitanate reagents', 'organometallic_partner', ['aryltitanate', 'arti(opr-i)4li', 'aryl titanate']),
        ('chlorotrimethylsilane', 'organometallic_partner', ['chlorotrimethylsilane', 'tmscl']),

        # 5. Ligands, chiral sources, and stereocontrolling elements
        ("chiral biaryl bisphosphine ligands", "ligand_or_chiral_source",["binap", "tms-binap", "segphos", "(s)-segphos", "(r)-segphos", "ecnu-phos", "meobiphep", "chiral biphenyl bisphosphine"]),
        ("achiral bisphosphine ligands for chirality transfer", "ligand_or_chiral_source",["dpephos", "wide-bite-angle bisphosphine", "non-chiral ligand", "achiral ligand-assisted chirality transfer"]),
        ("monodentate phosphine-type ligands", "ligand_or_chiral_source",["simplephos", "simplephos ligand", "meo-mop", "2-(diphenylphosphino)-2'-methoxy-1,1'-binaphthyl", "tributylphosphine", "pbu3", "trialkylphosphine"]),
        ("phosphite and phosphoramidite ligands", "ligand_or_chiral_source", ["phosphoramidite", "chiral phosphoramidite", "chiral phosphite", "phosphite ligand", "trialkyl phosphite"]),
        ("ferrocenyl and phosphametallocene phosphorus ligands", "ligand_or_chiral_source", ["ppfome", "bisppfome", "ferrocenyl monophosphine", "phosphametallocene", "phosphaferrocene", "phospharuthenocene"]),
        ("non-phosphorus metal-coordination ligands", "ligand_or_chiral_source", ["n-heterocyclic carbene", "nhc ligand", "palladium nhc", "gold(iii) salen complex", "salen ligand"]),
        ("chiral diene ligands", "ligand_or_chiral_source", ["chiral diene ligand", "fc-tfb", "ferrocenyl-substituted chiral diene"]),
        ("chiral Brønsted acid and base catalysts", "ligand_or_chiral_source", ["chiral phosphoric acid", "bisphosphoric acid", "chiral guanidine", "bicyclic guanidine"]),
        ("cinchona-derived and chiral ammonium catalysts", "ligand_or_chiral_source", ["cinchona", "quinine", "cinchonidine", "brucine", "cinchona-derived", "chiral ammonium salt", "quaternary ammonium catalyst"]),
        ("prolinol-derived and other chiral amine catalysts", "ligand_or_chiral_source", ["chiral amine", "chiral prolinol", "proline-derived amine","alpha,alpha-diphenylprolinol", "α,α-diphenylprolinol", "dpp chiral amine"]),

        # 6. Leaving groups
        ('acetate leaving groups', 'leaving_group', ['acetate leaving group', 'propargylic acetate', 'ethynylcarbinol acetate']),
        ('mesylate leaving groups', 'leaving_group', ['mesylate leaving group', 'methanesulfonate', 'propargylic mesylate']),
        ('tosylate and sulfonate leaving groups', 'leaving_group', ['tosylate', 'sulfonate leaving group', 'propargylic sulfonate']),
        ('sulfinate leaving groups', 'leaving_group', ['sulfinate', 'propargylic sulfinate']),
        ('carbonate leaving groups', 'leaving_group', ['carbonate leaving group', 'propargylic carbonate']),
        ('phosphate leaving groups', 'leaving_group', ['phosphate leaving group', 'propargylic phosphate']),
        ('halide leaving groups', 'leaving_group', ['chloride leaving group', 'bromide leaving group', 'iodide leaving group']),
        ('ether leaving groups', 'leaving_group', ['alkoxy leaving group', 'propargylic ether', 'methoxy group']),
        ('epoxide ring opening', 'leaving_group', ['epoxide opening', 'propargylic epoxide', 'oxirane opening']),
        ('carbamate leaving groups', 'leaving_group', ['carbamate leaving group', 'propargylic carbamate']),

        # 7. Reaction types
        ('formaldehyde-based terminal-alkyne homologation', 'reaction_type', ['crabbé homologation', 'homologation of acetylenes', 'formaldehyde-mediated allene synthesis', 'paraformaldehyde', 'terminal allenes from terminal alkynes', 'terminal allene from terminal alkyne']),
        ('aldehyde-based three-component ATA', 'reaction_type', ['terminal alkynes and aldehydes', '1-alkynes, aldehydes', 'aldehyde-derived iminium', 'aldehyde-alkyne-amine coupling', 'one-pot chiral amine ata', 'aryl-substituted allenes from terminal alkynes, aromatic aldehydes']),
        ('ketone-based three-component ATA', 'reaction_type', ['terminal alkynes and ketones', 'terminal alkyne and ketone', 'ketoniminium', 'ketones in a one-pot process', 'trisubstituted allenes from ketones']),
        ('allenation of terminal alkyne', 'reaction_type', ['allenylation of terminal alkynes', 'ata reaction', 'crabbé homologation', 'homologation of acetylenes', 'terminal allene from terminal alkyne', 'formaldehyde-mediated allene synthesis', 'terminal alkyne aldehyde amine allene synthesis', 'terminal alkyne ketone amine allene synthesis', 'one-pot chiral amine ata', 'bimetallic ata reaction', 'zn/cu-mediated terminal alkyne allenylation', 'tbs-directed alpha-allenol synthesis', 'protected propynol allenylation']),
        ('propargylamine formation and allene rearrangement', 'reaction_type', ['a3 coupling', 'aldehyde-alkyne-amine coupling', 'propargylamine formation', 'propargylamine to allene', 'propargylamine-to-allene transformation', 'hydride-transfer allene synthesis']),
        ('propargylic substitution and cross-coupling', 'reaction_type', ['gamma-selective coupling of propargylic electrophiles', 'γ-selective coupling of propargylic electrophiles', 'organocuprate 1,3-substitution', 'copper-mediated 1,3-substitution', 'propargylic 1,3-substitution', "sn2' substitution", 'sn2-prime substitution', 'propargylic substitution to allene', 'propargylic coupling with arylboronic acid', 'propargylic coupling with triorganoindium', 'propargylic carbonate organozinc coupling', 'dynamic kinetic asymmetric transformation of propargylic electrophiles']),
        ('enyne hydrofunctionalization to allenes', 'reaction_type', ['asymmetric hydroboration of 1,3-enynes', 'allenylborane synthesis from enyne', 'asymmetric hydrosilylation of 1,3-enynes', 'allenylsilane synthesis from enyne', 'hydrozirconation to allene', 'hydrozirconative allene synthesis', 'reduction with cp2zr(h)cl']),
        ('conjugate 1,6-addition to enynes', 'reaction_type', ['asymmetric 1,6-addition to enyne', 'rhodium-catalyzed 1,6-addition', '1,6-addition of aryltitanates', 'aryltitanate addition to enynone', '1,6-addition of arylboronic acids', 'arylboronic acid addition to enynamide']),
        ('carbonylative synthesis of allenes and allenoates', 'reaction_type', ['palladium-catalyzed carbonylation to allenoate', 'alkoxycarbonylation to allenoate', 'asymmetric carbonylation of propargylic carbonates', 'chirality-transfer carbonylation', 'carbonylation of propargylic mesylates', 'carbonylative allene synthesis']),
        ('ketene olefination to allenecarboxylates', 'reaction_type', ['ketene olefination', 'olefination of ketenes', 'wittig reaction of ketene', 'hwe synthesis of allenecarboxylates', 'p-chiral hwe allene synthesis', 'phosphinylacetate ketene olefination']),
        ('isomerization fragmentation and protonation to allenes', 'reaction_type', ['alkyne-to-allene isomerization', 'alkyne allene isomerization', 'prototropic rearrangement to allene', 'mitsunobu allene synthesis', 'mitsunobu-fragmentation allene synthesis', 'nbsh allene synthesis', 'dynamic kinetic protonation', 'asymmetric protonation of allenylmetal']),
        ('allenyl-reagent addition to carbonyl compounds', 'reaction_type', ['allenylborane addition to aldehyde', 'allenylborane addition to carbonyl compound', 'allenylmetal addition to aldehyde', 'allenylmetal addition to ketone', 'propynylation of aldehyde']),
        ('intermolecular functionalization of allenes', 'reaction_type', ['intermolecular hydroamination of allenes', 'hydrocarbonation of allenes', 'allylation of pronucleophiles with allenes', 'formal allylation with allene', 'heck-type coupling of allenes', 'cross-coupling of allenes', 'intermolecular addition to allene']),
        ('intramolecular cyclization and skeletal reorganization of allenes', 'reaction_type', ['allene cycloisomerization', 'intramolecular hydroamination of allenes', 'intramolecular hydroalkoxylation of allenes', 'nucleophilic cyclization of allenes', 'electrophilic cyclization of allenes', 'halolactonization of allenes', 'allenoic acid cyclization to butenolide', 'carbonylative cyclization of allenes', 'cyclic carbonylation of allenes', 'allene ring expansion']),
        ('cycloaddition and annulation of allenes', 'reaction_type', ['1,3-dipolar cycloaddition of allenes', '[3+2] cycloaddition of allenes', 'diels-alder reaction of vinylallenes', '[4+2] cycloaddition of vinylallenes', 'vinylallene cycloaddition', 'annulation involving allenes']),
        ('radical transformations of allenes', 'reaction_type', ['radical reaction of allenes', 'radical reaction of allenols', 'allenol radical reaction', 'radical addition to allene', 'radical cyclization of allenes']),

        # 8. Document scope
        ('primary research article', 'document_scope', ['research article', 'full paper', 'original research']),
        ('communication or letter', 'document_scope', ['communication', 'letter', 'short communication']),
        ('mechanistic study', 'document_scope', ['mechanistic study', 'mechanism investigation', 'intermediate study']),
        ('stereochemical study', 'document_scope', ['stereochemical study', 'syn or anti', 'configurational stability']),
        ('method optimization study', 'document_scope', ['optimization study', 'substrate scope', 'ligand screening']),
        ('application or total synthesis paper', 'document_scope', ['total synthesis', 'formal total synthesis', 'synthetic application']),
        ('account or perspective', 'document_scope', ['account', 'perspective', 'concept article']),
        ('comprehensive review', 'document_scope', ['review', 'comprehensive review', 'feature article']),
        ('book or book chapter', 'document_scope', ['book', 'monograph', 'book chapter']),
        ('historical paper', 'document_scope', ['historical paper', 'early report', 'classical study']),
        ('reproducibility or verification study', 'document_scope', ['reproducibility study', 'verification of reported procedure']),
        ('ligand-development study', 'document_scope', ['ligand development', 'phosphametallocene synthesis and application']),

]

verification_profile = {
    "chemical_suffixes": ["allene"],
    "soft_stereo_terms": ["axial chirality"],
    "cross_language_terms": [
        ["chirality transfer", ["手性转移", "轴手性向中心手性转移"]],
        ["axial-to-central", ["轴手性向中心手性转移", "轴手性", "中心手性"]],
        ["allenol", ["联烯醇"]],
        ["allene", ["联烯"]],
    ],
}
